language: r
sudo: false
cache: packages
r_github_packages:
- gaborcsardi/gh
r_packages:
- knitr
- drat
- covr
after_failure:
  email:
    recipients:
    - thosjleeper@gmail.com
    on_success: change
    on_failure: change
after_success:
- Rscript -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  drat.sh
env:
  global:
  - secure: lkrSZ+Pun5YmQ+6Dc04ZONTTetnrUbj4m1mSz9xy9OvbXBPuSnB00v5mOYL4T9YQZmMwbW6gw65EyTTUKmPVnk9Zh0uwZ28LGaDS6rPF28ssvGI/JjJa6yt3t2eHLr5IVM7+lY3ndHXcOzYbnNaZ/KQPeYKGG2tVAG7N0I7rviM/TdIms6lJwgWDnVaMZyDrSgiCoLqfq/Xj8v8QPEgIMz/UfRhFeR6Q9rLTXb6DCrHSRRDojN/TV1wz/b0Vm7cU/3GLWz0OQpMBqAMpq94G9sRWci6Db7RMkN9yEnB36zjVRgkIy8sEqADSO0CDPPP3LB8cEvfni03HiNapCWWZdRqoAbMM819vIhn5Eh5KrsVYIJtq575tE3XaY/S3JupWvFBAkW4LLknNkOq1A46kc5gm/1MM+FqHQk65LvWwkRkYvyQ6sPu4Oz7nTIrBl1TeVVF+btEPlEqsPyZkAQ/9TGbtZ7OCuoz0k+dIXZNnvz620sbe3NBUOPj5Z+/ptHQhYY2NZly8JVtQEaCckgDwVTIZWNdcz7dRx7NwNGpd1UNS3jBZl2W7/OWH/rzPsjQWxfq/PIx7MZZOkh9W9P+J46k/vD8zmZDdF5Fb8xq9e+kXgUB/q0GHzbpbPQ8mIj4FB+8Lv7OznN2Nv1ataRy4IdtCqunKeC2YJ9eUgYj33ug=
  - secure: llJ2ecB5xwGKnCwlSyoRhu5IEwO4WQ3K/iiakLE8pj6iIC93AREvQnh/dq8PZBF+HTM4Up9eLykhpmIHHa2EbUqUcmC6b+1D6ZnRSxT3FyKCN5IgU6LryS9Jfhn4oHjo7jk728zVDe7ZeRwQcTnw+K4JiM1QlY5/r25AouhW+IMxJs2/uaPm6eJ7Viad5FwPSVWl88tfJAsE5pDJQdx+uFzKIvAxvQn14p0jDlKpsCjwKtIbf/lIrtFLJrSL22owD2hcDMT16pr7zNt2D/blhzqFGUWxmtHgxNriOr3Qi5z5i5enXbjIGt0QqUeZuM+n0ukFDIsR9I+aEVNW/4PjR8ot2yBSoE9uD4YMkrDF1cK+00B+0+KxcTwMJXVKcpXgilwKwL5GMf4EIUWtSzdfePp1KTgZPOQ8L1Cp2/WVyzaxJFXniRKXTjbyIbc2sEirDurTVD1WRe5gAi6VBAGdxtTWm4wijbvu2mUh1xiMRCgz2zQrxP3JcPbpXlC7+QpzumJS2slkU3x0anS6ZD4tBuU8l/rUV7+bHt9D2IWOHfsA7CcV0czgUzaqxsWWrLyfq95ikrVlzBJqVTElXj4rDcEXEaR9Xj+i/r3/eH+igp0egxf5uLeTimtVNCOSo92mBYQAuCh6U62Mm4BLVcDG+RdnwYYb5uV5BZMCWWIEdXs=
